# Generated by Django 4.0.5 on 2022-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='costumuser',
            name='second_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='costumuser',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
