# Generated by Django 4.0.5 on 2022-06-27 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.AddField(
            model_name='products',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='postpic'),
        ),
        migrations.AddField(
            model_name='products',
            name='subtitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
